### PR TITLE
1) Remove reference of EntryReader to StoredEntry. 2) don't use opaque type in SyncStoredReader::reader

### PR DESCRIPTION
**Pull request by muja**
Currently it's necessary to have 4 separate variables to read:

```rust
let f = std::fs::File(p)?;
let zip = f.read_zip()?;
let entry = zip.by_name("foo")?;
let reader = entry.reader();
// start reading
```

This PR makes it possible to combine lines 3 and 4:

```rust
let reader = zip.by_name("foo")?.reader();
```

It's probably also faster because the copies are very small and the entry needs not be derefenced here, but that was not my primary goal.

The 2nd part is the opaque type which makes it hard for users to specify it in non-impl places. I saw no benefit in that.

If desired, I can split the PRs per commit.

### CODE REVIEW

**Comment by fasterthanlime** [comment]
How would you feel about getting commit rights for this repo?

You seem to care about it more than I do right now, I’m happy to let you take it where you think it needs to go for now!

**Comment by fasterthanlime** [comment]
> How would you feel about getting commit rights for this repo?
> 
> You seem to care about it more than I do right now, I’m happy to let you take it where you think it needs to go for now!

@muja I’ve just added you as collaborator for this repo — you may need to accept the invite. Once that’s done, feel free to merge this PR!

**Comment by muja** [comment]
I don't know if that's a good idea. I know next to nothing about the ZIP format and also wouldn't feel comfortable committing code here without having them reviewed since I also don't know about the usage patterns in the wild or when something's a breaking change. For that, the test coverage is too low I imagine. But maybe it's possible to reach out to past contributors whether they would be up for it.

**Comment by fasterthanlime** [comment]
> I don't know if that's a good idea. I know next to nothing about the ZIP format and also wouldn't feel comfortable committing code here without having them reviewed since I also don't know about the usage patterns in the wild or when something's a breaking change. For that, the test coverage is too low I imagine. But maybe it's possible to reach out to past contributors whether they would be up for it.

So! There's no past contributors, not really (@geal reviewed some early drafts but that's about it), and as you can see, rc-zip is barely used: https://lib.rs/crates/rc-zip/rev

You can go ahead and merge this PR - if you have doubts for subsequent PRs, feel free to ping me and I'll take a look.

**Comment by muja** [comment]
There are the authors of #17 and #18 who may be candidates. But I'll accept your invitation.

> and as you can see, rc-zip is barely used: https://lib.rs/crates/rc-zip/rev

Yeah I was wondering about that. The fact that this can extract files in parallel and doesn't mutate the file makes this extremely handy. 

Also I found out that `circular` [exposes UB under Stacked Borrows](https://github.com/sozu-proxy/circular/issues/9).

**Comment by fasterthanlime** [comment]
> Also I found out that `circular` [exposes UB under Stacked Borrows](https://github.com/sozu-proxy/circular/issues/9).

That's a good point - I'm not sure it's actively being maintained, getting rid of the dependency could be a good exercise if you want to get more familiar with rc-zip!

I'm not sure I would go with the same architecture nowadays tbh. It's really awkward to work with. But.. it should be fairly correct.

**Comment by fasterthanlime** [comment]
I'm looking at this again, I like the changes with a couple tune-ups, I'll merge this as-is and adjust later!

**Pull request merged**
